server:
  port: 8070
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/authserverexample
    username: ${app.secret.datasource.username}
    password: ${app.secret.datasource.password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  redis:
    host: localhost
    port: 6379
    ssl: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${app.secret.mail.username}
    password: ${app.secret.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090 # http://localhost:8081/sso-auth-server/.well-known/jwks.json

app:
  auth:
    base-url: http://localhost:${server.port}
    jwt:
      keystore: classpath:jwt.p12
      keystore-password: ${app.secret.auth.jwt.keystore-password}
      key-alias: ${app.secret.auth.jwt.key-alias}
      key-password: ${app.secret.auth.jwt.key-password}
      access-token-validity-seconds: 3600
      refresh-token-validity-seconds: 86400
    otp:
      code-length: 6
      ttl-minutes: 5
